### ISSUE TITLE
Running as a service

### ISSUE THREAD

**Issue by BillBuilt** [acaloiaro/neoq#105]
Hello,

We've ran into an issue where scheduled jobs (run later) do not get executed when Neoq is running as a service. I don't have the time to work out an example ATM but it should be fairly easy to set this up. Use logging to see when everything happens:

1. Run an instance of Neoq as s service by instantiating Neoq and then loading the handlers. Keep this running by using an empty `select{}` or other means. 
2. In another app, instantiate Neoq and load at minimum 2 jobs:
  - 1 instant job
  - 1 scheduled job (now + 5 seconds, for example)
3. What we would expect to happen is that the "service" launched in step 1 would pick up the jobs that the app in step 2 creates and we would see the instant job run and then 5 seconds later the scheduled job. 
  - What we have been observing is that the instant job is discovered and is processed and executed, but the scheduled job is basically ignored and never runs.
  - It doesn't matter if the job returns an error. If this happens for an instant job, error handling and retires work fine. If a scheduled job returns an error, same thing occurs - it is ignored.

Thank you

**Comment by acaloiaro** [comment]
Hi Bill, can you tell me which backend you're referring to? I'm also not exactly sure what you mean by "as a service". In my mind, if neoq is running, it's always running as a service. 

Let me know if I'm following the rest correct.

Step (1.) you're calling `Start()` for two separate queues, likely with two separate handlers.
Step (2.) you're calling `Enqueue()` with future jobs (they have `RunAfter` explicitly set), targeting the handlers started in (1.)

**Comment by acaloiaro** [comment]
@BillBuilt ping to see if you're still having issues with this
