### ISSUE TITLE
Run multi periodic jobs

### ISSUE THREAD

**Issue by felipelyp** [acaloiaro/neoq#110]
**How do I run periodic multi jobs?**
I tried some ways and couldn't, so I decided to ask for help so I could understand a little.

![image](https://github.com/acaloiaro/neoq/assets/28626603/973e1e7f-1d98-4169-8c18-4748d4692168)

**Comment by acaloiaro** [comment]
Hi @felipelyp -- could you tell me what behavior you expect from the above code? 

I believe the behavior of the above code is that `h2` overwrites the cron schedule for `* * * * * *`, meaning that `h2` runs every second. 

If you'd like to run multiple jobs per second, you can create a single handler that does multiple things, e.g.

```go
h := handler.NewPeriodic(func(ctx context.Context) (err error) {
   doFirstThing()
   doSecondThing()
   return
})
```
And if you'd like to run code in parallel every second, 

```go
h := handler.NewPeriodic(func(ctx context.Context) (err error) {
   go func() { doFirstThing() }()
   go func() { doSecondThing() }()
   return
})
```

Hope this helps.

**Comment by felipelyp** [comment]
Thanks you
