### ISSUE TITLE
Consider changing license?

### ISSUE THREAD

**Issue by philwinder** [acaloiaro/neoq#115]
Hi there,
I had a need for a simple queuing system with swappable storage options. And neoq has worked great!

But I'm developing a commercial product and I've just noticed the agpl license. This means I'm going to have to swap it out for something more permissive.

Before I do, would you consider changing the license to allow commercial use?

Thanks, Phil

**Comment by acaloiaro** [comment]
Yeah consider it done. I actually need this change for myself, too. Cheers.

**Comment by acaloiaro** [comment]
Done! Enjoy

**Comment by philwinder** [comment]
Thank you!
