### ISSUE TITLE
Context not initialized with job before use

### ISSUE THREAD

**Issue by pconstantinou** [acaloiaro/neoq#123]
I've got a process that gets stuck in a loop on launch with this error:
```
16:45:04: job failed" queue=alert error="error getting job from context: context has no Job" job_id=4
16:45:04: job failed" job_error="the job did not complete before its deadline
```

Looking at this:
https://github.com/acaloiaro/neoq/blob/main/backends/postgres/postgres_backend.go#L858

```
	if job.Deadline != nil && job.Deadline.Before(time.Now().UTC()) {
		err = jobs.ErrJobExceededDeadline
		p.logger.Debug("job deadline is in the past, skipping", slog.String("queue", job.Queue), slog.Int64("job_id", job.ID))
		err = p.updateJob(ctx, err)
		return
	}

	ctx = withJobContext(ctx, job)
	ctx = context.WithValue(ctx, txCtxVarKey, tx)
```

It looks like the job is not added to the context before the calling `updateJob`.

**Comment by acaloiaro** [comment]
Thanks for the report @pconstantinou. This is a clear bug.

**Comment by acaloiaro** [comment]
Fixed in [v0.62.0](https://github.com/acaloiaro/neoq/releases/tag/v0.62.0)

**Comment by pconstantinou** [comment]
I patched my fork but I'm not sure if that's the end of the problem. 

It looks like the transaction that's started here:
https://github.com/acaloiaro/neoq/blob/main/backends/postgres/postgres_backend.go#L844

isn't committed if the Deadline error returns here:
https://github.com/acaloiaro/neoq/blob/main/backends/postgres/postgres_backend.go#L858

So, this statement:
https://github.com/acaloiaro/neoq/blob/main/backends/postgres/postgres_backend.go#L611

is rolled back.

I still have the problem that, when the earliest `run_after` transaction has passed it's deadline on start up, the server goes into an infinite loop polling the database.

I suspect this is because it doesn't commit the error state of the transaction.

I'm going to try to commit the transaction when the deadline is hit. I worked around the problem by deleting the bad jobs so I don't have a great test case.

**Comment by acaloiaro** [comment]
Looks like you're right about that. The error returns correctly (which the test case handles), but the test case doesn't cover ensuring the the job's status is updated correctly. 

There should be `tx.Commit(ctx)` after updating the status.

**Comment by acaloiaro** [comment]
@pconstantinou Feel free to check out `v0.62.0` for the fix.
