### ISSUE TITLE
feat: Support for SQLite backend

### ISSUE THREAD

**Issue by pranavmodx** [acaloiaro/neoq#129]
Hi Adriano, 

Thanks for creating this amazing library! We have used it at our organization and it fits really well for our use cases. 

The main requirement for us was that we needed a job queue backend which was **persistent** and **embeddable** in our application. As far as we could see, currently no job queuing library in Go has support for embedded databases like `SQLite`. So we were on the lookout to maybe extend an existing library or write one from scratch in the worst case. But thanks to the simplicity of **neoq**, we decided to implement SQLite backend for it to be able to use most (and eventually all) of neoq's features. 

Here is the **fork of neoq** which implements SQLite backend: https://github.com/pranavmodx/neoq-sqlite
SQLite doesn't seem to have a built-in notification system as that in PostgreSQL (pg_notify). So I have used Go channels as a mechanism similar to how you have used it for in-memory queue backend. The overall changes may need some refactoring and addition of unit tests.

Would you be interested in reviewing this effort and considering it as an open source contribution?

Thanks,
Pranav

**Comment by acaloiaro** [comment]
@pranavmodx I'm absolutely interested in merging SQLite support. Thank you for contributing back!

A few things we should consider requirements for merging new backends

- Feature parity with existing backends. I think _some_ exceptions to this rule may be reasonable, but I'd like to deal with them on a case-by-case basis. Feature parity theoretically makes it easy to swap out different backends within one's application without needing to change much application code. 
- Roughly the same amount of test coverage as existing backends. I believe the existing backends are between 60 and 80% coverage right now. Which is actually lower than I'd like coverage to be, so asking for roughly the same coverage seems reasonable. But more would be better if reasonable. 

Let's get your work under review whenever you're ready. Feel free to join the Matrix chat from the README if you want to discuss anything further. 

Cheers
