### ISSUE TITLE
feature request: ability to issue jobs to queue with included Time To Live duration

### ISSUE THREAD

**Issue by c-nv-s** [acaloiaro/neoq#52]
In some use cases it is very handy to be able to automatically remove a job from the queue if it has not been worked by a specified time duration.

 This request is to implement an option/mechanism which allows the developer to specify a duration or Time To Live (TTL) for the job/s issued to the queue.
 
Personally, I'm not too precious about whether the developer is allowed to set the option at client creation or per request, but I understand that others may be more opinionated about it.

**Comment by acaloiaro** [comment]
Thanks for the request. I'll be mulling over its implications and considering it for implementation in the coming days. 

The TTL concept too me _feels_ like a job-level property expressed in `time.Duration`.

**Comment by acaloiaro** [comment]
This feature requires a database migration for postgres. Migration support added here: https://github.com/acaloiaro/neoq/pull/58

**Comment by c-nv-s** [comment]
awesome!! I'll see if I can test this out over the weekend
