### ISSUE TITLE
Multi node cron jobs.

### ISSUE THREAD

**Issue by elliotcourant** [acaloiaro/neoq#76]
At the moment if you were to start a neoq worker on 2 different nodes with a single PostgreSQL backend and have crons configured for them. 

Every time a cron would be scheduled, one node will ultimately insert the cron into the jobs table while the other nodes fail with an error `level=ERROR msg="error queueing cron job" error="duplicate job"`.

Is the intended use case that a single node would orchestrate the enqueuing of these crons? Or that the contention and resulting error about duplicate job from the additional nodes is intended?

**Comment by elliotcourant** [comment]
A potential solution to this that would at least cut down on the error logs might be something like:

```patch
diff --git a/backends/postgres/postgres_backend.go b/backends/postgres/postgres_backend.go
index 1d76b714..dd8fc01b 100644
--- a/backends/postgres/postgres_backend.go
+++ b/backends/postgres/postgres_backend.go
@@ -358,7 +358,7 @@ func (p *PgBackend) StartCron(ctx context.Context, cronSpec string, h handler.Ha
 	if err = p.cron.AddFunc(cronSpec, func() {
 		_, err := p.Enqueue(ctx, &jobs.Job{Queue: queue})
 		if err != nil {
-			if errors.Is(err, context.Canceled) {
+			if errors.Is(err, context.Canceled) || errors.Is(err, ErrDuplicateJob) {
 				return
 			}
```

This way when two workers each try to produce the same cron at the same(ish) time, you don't end up with logs regarding a duplicate since that log is not useful for a cron that has already been created.


---


But a better solution might be moving the crons themselves into a table where the next execution of the cron job as part of the table.

```sql
CREATE TABLE cron_jobs (
  slug        TEXT NOT NULL PRIMARY KEY,
  schedule    TEXT NOT NULL,
  next_run_at TIMESTAMP WITH TIME ZONE NOT NULL
);
```

This table could then be queried as such:

```sql
SELECT cron_jobs.*
FROM cron_jobs
WHERE next_run_at <= now()
ORDER BY next_run_at ASC
FOR UPDATE SKIP LOCKED
LIMIT 1;

UPDATE cron_jobs SET next_run_at = $1 WHERE slug = $2;
```

Adapted to neoq, the select query could retrieve only the cron that it is handling when its own cron timer tells it that it should be processed. But since the row would be locked or the timestamp would already be bumped by another node, it would only retrieve the cron for processing if it is properly the first one to request it.

**Comment by acaloiaro** [comment]
I like the first solution for its simplicity. My preference is to push as much responsibility as possible onto the PG server. 

Correct me if I'm wrong, but the second solution models with data (the new `next_run_at` field) what the first one models with the simple cron specification in code (well it's a string, but it's a user-supplied string in code).

**Comment by elliotcourant** [comment]
Yeah the second approach basically turns the unique constraint competition with that fingerprint into just a lock competition. There might be an objectively better one of the two performance wise from PG's perspective? But I have no idea what it is.

I think silencing the `ErrDuplicateJob` for now would be fine, and see how long that goes without the _need_ for more complexity.

**Comment by acaloiaro** [comment]
I agree. If or when the performance of this implementation proves inadequate, your second approach should be considered.

**Comment by elliotcourant** [comment]
Reopening

```
=== Failed
=== FAIL: backends/postgres TestMultipleCronNodes (3.18s)
==================
WARNING: DATA RACE
Read at 0x00c0000a687c by goroutine 4624:
  github.com/acaloiaro/neoq/backends/postgres_test.TestMultipleCronNodes()
      /__w/neoq/neoq/backends/postgres/postgres_backend_test.go:432 +0x924
  testing.tRunner()
      /usr/local/go/src/testing/testing.go:1576 +0x216
  testing.(*T).Run.func1()
      /usr/local/go/src/testing/testing.go:1629 +0x47

Previous write at 0x00c0000a687c by goroutine 5174:
  sync/atomic.AddInt32()
      /usr/local/go/src/runtime/race_amd64.s:281 +0xb
  sync/atomic.AddUint32()
      <autogenerated>:1 +0x1a
  github.com/acaloiaro/neoq/handler.Exec.func1()
      /__w/neoq/neoq/handler/handler.go:137 +0xe2
  github.com/acaloiaro/neoq/handler.Exec.func2()
      /__w/neoq/neoq/handler/handler.go:138 +0x58

Goroutine 4624 (running) created at:
  testing.(*T).Run()
      /usr/local/go/src/testing/testing.go:1629 +0x805
  testing.runTests.func1()
      /usr/local/go/src/testing/testing.go:2036 +0x8d
  testing.tRunner()
      /usr/local/go/src/testing/testing.go:1576 +0x216
  testing.runTests()
      /usr/local/go/src/testing/testing.go:2034 +0x87c
  testing.(*M).Run()
      /usr/local/go/src/testing/testing.go:1906 +0xb44
  github.com/acaloiaro/neoq/backends/postgres_test.TestMain()
      /__w/neoq/neoq/backends/postgres/postgres_backend_test.go:78 +0x2e
  main.main()
      _testmain.go:94 +0x33d

Goroutine 5174 (finished) created at:
  github.com/acaloiaro/neoq/handler.Exec()
      /__w/neoq/neoq/handler/handler.go:[115](https://github.com/acaloiaro/neoq/actions/runs/6434396784/job/17473540486#step:4:116) +0x309
  github.com/acaloiaro/neoq/backends/postgres.(*PgBackend).handleJob()
      /__w/neoq/neoq/backends/postgres/postgres_backend.go:732 +0x924
  github.com/acaloiaro/neoq/backends/postgres.(*PgBackend).start.func2()
      /__w/neoq/neoq/backends/postgres/postgres_backend.go:549 +0x32f
==================
time=2023-10-06T17:10:09.006Z level=ERROR msg="error enqueueing job" error="unable add job to queue: context canceled"
time=2023-10-06T17:10:09.006Z level=ERROR msg="error queueing cron job" error="error committing transaction: conn closed"
    testing.go:1446: race detected during execution of test

DONE 115 tests, 1 failure in [137](https://github.com/acaloiaro/neoq/actions/runs/6434396784/job/17473540486#step:4:138).274s
make: *** [Makefile:22: test] Error 1
```
