### ISSUE TITLE
MaxRetries not getting set

### ISSUE THREAD

**Issue by BillBuilt** [acaloiaro/neoq#85]
Job `MaxRetries` field is not being saved and always defaults to '23':

https://github.com/acaloiaro/neoq/blob/de2e101736644178505d943ec4d449253b152ada/backends/postgres/postgres_backend.go#L422

**Comment by BillBuilt** [comment]
Thanks! FWIW: I could not find any references to "max retries" in any of the backends, but I wasn't searching very thoroughly in the others.

**Comment by acaloiaro** [comment]
Retries for the Redis backend are implemented in `asynq`. However, the mem backend also appears to not be handling max retries correctly and that'll need to be fixed as well. 

I'll use this as an opportunity to increase test coverage.

**Comment by acaloiaro** [comment]
Hi @BillBuilt I'm going to go ahead and merge the postgres fix for you and open up a new issue to work on the mem backend. Thanks for the report!

**Comment by BillBuilt** [comment]
Just in time for my unit tests! Thank you!

Bill

**Comment by acaloiaro** [comment]
Excellent!
